### PR TITLE
Pyth Sample EVM Price Feeds

### PR DESCRIPTION
**Pull request by aditya520**

### CODE REVIEW

**Comment by ali-bahjati** [comment]
What's the purpose of this example?

**Comment by aditya520** [comment]
This is kind of hello-world example that is requested by alot of new devs during hackathons.

**Review by ali-bahjati — APPROVED** [review]
LGTM. I think a good helloworld one can be even simpler, get a price and emit a log for it.

**Comment by aditya520** [comment]
I wanted to show that one can update multiple prices in a single call. That's why we have two methods.

**Pull request merged**
